const AssemblyI18n=(()=>{
 let language='en',originalData=null;const cache=new WeakMap(),attributeCache=new WeakMap();
 const names={flhDC:'Master transcriptional regulator',fliF:'MS-ring protein',fliG:'Rotor / switch protein',fliM:'Switch-complex protein',fliN:'C-ring protein',export:'Membrane export gate',flhAB:'Export / substrate switching',fliHIJ:'Export ATPase complex',rod:'Rod protein group',flgG:'Distal rod protein',flgI:'P-ring protein',flgH:'L-ring protein',flgD:'Hook cap / scaffold',flgE:'Hook protein',fliK:'Hook-length control',flgKL:'Hook–filament junction',fliD:'Filament cap',fliC:'Flagellin',motAB:'H⁺ stator',flhF:'Polar-localization GTPase',flhG:'Flagellar-number ATPase',fliMN:'Switch / C ring',flgT:'H-ring scaffold',motXY:'T ring / stator assembly',flgDE:'Hook scaffold / hook',pomAB:'Na⁺ stator',sigD:'Late flagellar sigma factor',fliMY:'Switch / C ring',fliW:'Flagellin translation regulator',motPS:'Na⁺ stator',doubleStator:'Deletion of both stator systems'};
 const roles={flhDC:'Initiates expression of class 2 flagellar genes.',fliF:'Forms the membrane scaffold for basal-body assembly.',fliG:'Links the rotor to FliF and receives torque from stators.',fliM:'Contributes to the C ring and directional switching.',fliN:'Contributes to the switch complex and export apparatus coupling.',export:'Forms the membrane gate for export of axial proteins.',flhAB:'Contributes to flagellar type III export and substrate switching.',fliHIJ:'Delivers export substrates to the gate; residual export can persist in some conditions.',rod:'Forms the drive shaft extending from the basal body.',flgG:'Forms the distal rod passing through the LP bearing.',flgI:'Forms a bearing at the peptidoglycan layer.',flgH:'Forms the outer-membrane bearing.',flgD:'Provides the scaffold for FlgE polymerization.',flgE:'Forms the flexible hook connecting rod and filament.',fliK:'Controls hook length and switching to late export substrates.',flgKL:'Connects the hook tip to the filament base.',fliD:'Promotes flagellin polymerization at the filament tip.',fliC:'Provides a major structural subunit of the filament.',motAB:'Converts proton flow into torque.',flhF:'Contributes to polar positioning and efficient flagellar formation.',flhG:'Restrains polar flagellar number through regulation of FlhF.',fliMN:'Contributes to directional switching and export coupling.',flgT:'Supports H-ring formation and the stability of the polar motor.',motXY:'Contributes to the T ring and recruitment of PomA/PomB stators.',flgDE:'Contributes to hook initiation and polymerization.',pomAB:'Converts sodium flow into torque in the polar motor.',sigD:'Activates late flagellar and motility genes, including hag.',fliMY:'FliY shares functions associated with FliN in B. subtilis.',fliW:'Regulates hag translation through CsrA.',motPS:'Provides sodium-driven torque under conditions favoring MotPS.',doubleStator:'Removing both stator systems eliminates torque while structures can remain.'};
 const endpoints={
 'べん毛構造を形成しない':'No flagellar structure', 'MSリング以前で停止':'Arrest before MS-ring assembly','初期基部で停止・不安定化':'Early basal-body arrest / destabilization','Cリング形成不全':'Defective C-ring assembly','MS/Cリング段階で停止':'Arrest at the MS/C-ring stage','輸送効率が大幅低下':'Strongly reduced export efficiency','ロッド形成途中で停止':'Arrest during rod assembly','遠位ロッドを形成できない':'No distal rod','ロッドまで；Pリングなし':'Rod present; no P ring','Pリングまで；Lリングなし':'P ring present; no L ring','ロッドまで；フックなし':'Rod present; no hook','polyhookを形成':'Polyhook formation','フックまで；フィラメントなし':'Hook present; no filament','無キャップの短い／不安定なフィラメント':'Uncapped, short / unstable filament','フック・継ぎ手まで；フィラメントなし':'Hook and junction; no filament','完成するが回転しない':'Assembled but not rotating','べん毛数減少・異所性形成':'Reduced number / ectopic flagella','極べん毛が過剰化':'Excess polar flagella','基部外周リングが不安定':'Unstable peripheral basal-body rings','完成構造はあり得るが固定子装着不全':'Structures may form; defective stator recruitment','フィラメントが減少・形態異常':'Reduced / abnormal filaments','主にフィラメント形成前で停止':'Mainly impaired before filament formation','フィラメント量・運動性が低下':'Reduced filaments / motility','構築は完成；MotPSが部分代替':'Assembled; partial compensation by MotPS','構築は完成；MotABが代替':'Assembled; compensation by MotAB'};
 const caveats={fliHIJ:'Residual low-efficiency export may persist, depending on conditions.',fliK:'An elongated hook forms; this is not a simple linear arrest.',fliD:'Flagellin can be secreted without efficient assembly of a long filament.',flhF:'The primary change concerns placement and number, not a simple assembly arrest.',flhG:'The modeled phenotype is excess polar flagella, rather than structural loss.',flgT:'Peripheral-ring disruption and reduced assembly efficiency do not imply complete late-stage arrest.',fliC:'Multiple polar flagellins can compensate; a single flaA deletion need not eliminate filaments.',sigD:'Early structures can form, but effects extend across the SigD regulon.',fliW:'This is translational regulation rather than deletion of a structural component; effects vary with culture conditions.'};
 const pairs=Object.entries(endpoints).concat([
 ['欠損で、どこまで組み上がるか','How far does assembly proceed after a deletion?'],['判定基準・文献','Scope & references'],['菌種を選択','Select species'],['欠損タンパク質','Deleted protein'],['遺伝子名・機能で検索','Search gene or function'],['分類で絞り込み','Filter by function'],['タンパク質一覧','Protein catalog'],['凡例','Legend'],['構築される','Built'],['欠損の影響点','Affected'],['形成されない','Absent'],['べん毛構築停止段階','Flagellar assembly endpoint'],['選択したタンパク質を欠損したときに構築される部分と形成されない部分を示す模式図','Schematic of predicted structures after the selected deletion'],['構築段階','Assembly stages'],['表現型から欠損候補を絞り込む','Find deletion candidates from phenotypes'],['条件をクリア','Clear observations'],['上で選択した菌種が対象です。観察できた項目だけを選んでください。','Applies to the selected species. Enter only observations you have made.'],['収載された構築モデルとの照合であり、検証済みの予測器・確率ではありません。同じ表現型を示す遺伝子は区別できず、株・培養条件・極性効果・未収載遺伝子も影響します。複数遺伝子のカードは群単位の候補です。','Matches the catalog model, not a validated predictor or probability. Genes with identical modeled phenotypes cannot be separated. Strain, culture conditions, polar effects and unlisted genes matter. Multi-gene cards represent groups.'],['4菌種で対応関係を比較','Compare counterparts across four species'],['全収載遺伝子から比較','Choose any cataloged gene'],['判定基準と注意点','Scope and interpretation'],['主要文献','Registered references'],['閉じる','Close'],['すべて','All'],['該当するタンパク質がありません。','No matching proteins.'],['UniProt検索','UniProt search'],['菌種・遺伝子名で絞った対応候補。株と配列を確認してエントリーを選んでください。','Candidates filtered by species and gene. Verify strain and sequence before selecting an entry.'],['通常の役割','Normal role'],['解釈上の注意','Interpretation notes'],['菌種間の対応','Cross-species counterparts'],['対応タンパク質を収載していません','No counterpart in this catalog'],['未観察／不明','Not observed / unknown'],['表現型を選ぶと候補と照合根拠が表示されます。','Select observations to display candidates and matching criteria.'],['項目で照合。矛盾が少ない順、次に一致が多い順（同点は同順位）。「未判定」は一致に数えません。',' observations. Sorted by fewest conflicts, then most matches. Ties are equivalent. Unknowns do not count as matches.'],['：モデルでは',': model predicts '],['一致：','Matches: '],['矛盾：','Conflicts: '],['未判定：','Unknown: '],['一致 ','Matches '],['矛盾 ','Conflicts '],['未判定 ','Unknown '],['追加観察の提案','Suggested next observations'],['野生型との並列比較','Compare with wild type'],['野生型（基準モデル）','Wild type (reference model)'],['根拠の確認状況','Evidence audit status'],['モデル推定・原著照合待ち','Model inference · source audit pending'],['モデル予測と原著の実験結果を区別します。文献リンクは登録情報であり、各欠損の直接証拠を保証しません。','Model predictions are separate from experimental findings. Registered links do not certify direct evidence for each deletion.'],['原著の株・実験条件・図番号が未確認の項目は未照合と表示します。','Unaudited strain, experimental conditions and figure numbers are marked explicitly.'],['追加観察は矛盾のない候補を対象に、既知の予測が異なる組合せ数で順位付けします。未知の結果は候補除外に使いません。','Next observations are ranked by distinguishable pairs among candidates without conflicts. Unknown predictions never exclude a candidate.'],['株、培地、発現量、極性効果で表現型が変わる場合があります。','Phenotypes may vary with strain, medium, expression and polar effects.'],
 ['固定子・輸送装置の「あり／なし」は模式図での組立・局在を示します。細胞内のタンパク質発現量とは異なります。観察できていなければ未観察のままにしてください。','Present / absent for stators and export components means modeled assembly or localization, not protein expression level. Leave unobserved structures unset.'],['制御・配置','Regulation / placement'],['モーター回転','Motor rotation'],['モーター','Motor'],['輸送装置','Export apparatus'],['フィラメント','Filament'],['フック','Hook'],['ロッド','Rod'],['リング','Ring'],['発現・配置','Expression / placement'],['長さ制御','Length control'],['継ぎ手','Junction'],['回転機能','Rotation'],['固定子','Stator'],['数・配置','Number / placement'],['条件依存／低下','Conditional / reduced'],['短い／不安定','Short / unstable'],['異常に長い','Abnormally long'],['通常長','Normal length'],['異常','Abnormal'],['あり','Present'],['なし','Absent'],['相同推定','Homology inference'],['エビデンス',' evidence'],['直接','Direct']
 ]);
 function localizeData(){
  if(!originalData)originalData={species:JSON.parse(JSON.stringify(species)),categories:{...categoryNames},stages:[...stageNames],fields:JSON.parse(JSON.stringify(phenotypeFields)),groups:JSON.parse(JSON.stringify(compareGroups))};
  const enCategory={control:'Regulation / placement',motor:'Motor',export:'Export apparatus',rod:'Rod',rings:'Rings',hook:'Hook',filament:'Filament'};
  Object.assign(categoryNames,language==='en'?enCategory:originalData.categories);
  const enStages=['Expression / placement','MS ring','C ring / export','Rod','P/L / peripheral rings','Hook','Length control','Junction','Filament','Rotation'];stageNames.splice(0,stageNames.length,...(language==='en'?enStages:originalData.stages));
  const enOptions={rod:['Rod',{present:'Present',absent:'Absent'}],pRing:['P ring',{present:'Present',absent:'Absent'}],lRing:['L ring',{present:'Present',absent:'Absent'}],hook:['Hook',{present:'Present (length unknown)',absent:'Absent',long:'Abnormally long'}],filament:['Filament',{present:'Present',absent:'Absent',abnormal:'Reduced / abnormal'}],rotation:['Motor rotation',{present:'Present',absent:'Absent',reduced:'Conditional / reduced'}],statorEngagement:['Stator engagement',{present:'Present',partial:'One system only',absent:'Absent'}],exportGate:['FliPQR gate',{present:'Present',absent:'Absent'}],exportPlatform:['FlhAB structure',{present:'Present',absent:'Absent'}],exportAtpase:['FliHIJ complex',{present:'Present',absent:'Absent'}],placement:['Number / placement',{abnormal:'Abnormal'}]};
  phenotypeFields.forEach((f,i)=>{const src=originalData.fields[i];f[1]=language==='en'?enOptions[f[0]][0]:src[1];f[2]=language==='en'?enOptions[f[0]][1]:src[2]});
  for(const [id,s] of Object.entries(species)){const original=originalData.species[id];s.distribution=language==='en'?(id==='vibrio'?'Polar':'Peritrichous'):original.distribution;s.strain=language==='en'?({ecoli:'K-12 type · peritrichous · H⁺ driven',salmonella:'Serovar Typhimurium · peritrichous · H⁺ driven',vibrio:'Polar flagellum only · sheathed · Na⁺ driven',bacillus:'Subtilis 168/3610 types · peritrichous · Gram positive'}[id]):original.strain;s.proteins.forEach((p,i)=>{const o=original.proteins[i];for(const k of ['name','func','endpoint','caution'])p[k]=o[k];if(language==='en'){p.name=names[p.key];p.func=roles[p.key];p.endpoint=endpoints[o.endpoint];p.caution=o.caution?(caveats[p.key]||'Effects depend on strain and experimental conditions.'):'';Object.assign(p,o.en||{})}})}
  compareGroups.forEach((g,i)=>g.label=language==='en'?originalData.groups[i].label.split('｜')[0]+' | '+(names[g.keys[0]]||enCategory[g.category]):originalData.groups[i].label);
 }
 pairs.push(['バクテリアべん毛は、欠損でどこまで組み上がるか','How far does bacterial flagellar assembly proceed after a deletion?'],['バクテリアべん毛の構築停止段階','Bacterial flagellar assembly endpoint'],['バクテリアべん毛のタンパク質を欠損したときに構築される部分と形成されない部分を示す模式図','Diagram of modeled bacterial flagellar structures after a protein deletion'],['P/Lリング・固定子・輸送装置の「あり／なし」は模式図での組立・局在を示します。細胞内のタンパク質発現量とは異なります。観察できていなければ未観察のままにしてください。P/Lリングは外膜を持つ菌種のみ表示します。','Present / absent for P/L rings, stators and export components means modeled assembly or localization, not protein expression. Leave unobserved structures unset. P/L ring controls appear only for outer-membrane species.']);
 pairs.sort((a,b)=>b[0].length-a[0].length);
 function t(s){if(language==='ja')return s;for(const [a,b] of pairs)s=s.split(a).join(b);return s}
 function apply(root=document.body){if(root.nodeType===3){if(['SCRIPT','STYLE'].includes(root.parentElement?.tagName))return;const old=cache.get(root),original=old&&root.nodeValue===old.shown?old.original:root.nodeValue,shown=t(original);if(root.nodeValue!==shown)root.nodeValue=shown;cache.set(root,{original,shown});return}if(root.nodeType!==1||['SCRIPT','STYLE'].includes(root.tagName))return;for(const a of ['aria-label','placeholder','label'])if(root.hasAttribute(a)){const stored=attributeCache.get(root)||{},old=stored[a],v=root.getAttribute(a),original=old&&v===old.shown?old.original:v,shown=t(original);if(v!==shown)root.setAttribute(a,shown);stored[a]={original,shown};attributeCache.set(root,stored)}for(const node of root.childNodes)apply(node)}
 function setLanguage(next){const observations=Object.fromEntries(visiblePhenotypeFields().map(([key])=>[key,$('#phenotype-'+key).value])),compare=$('#compareGene').value;language=next;document.documentElement.lang=next;localizeData();renderSpecies();renderFilters();renderCompareOptions();selectProtein(state.selected,compare);initPhenotypes();visiblePhenotypeFields().forEach(([key])=>$('#phenotype-'+key).value=observations[key]||'');renderPredictions();apply();$('#languageButton').textContent=next==='en'?'Japanese':'English'}
 function start(){localizeData();document.documentElement.lang='en';const b=document.createElement('button');b.id='languageButton';b.className='method-button';b.textContent='Japanese';b.onclick=()=>setLanguage(language==='en'?'ja':'en');document.querySelector('.topbar').appendChild(b);apply();new MutationObserver(rs=>rs.forEach(r=>r.type==='characterData'?apply(r.target):r.addedNodes.forEach(apply))).observe(document.body,{childList:true,characterData:true,subtree:true})}
 return {t,start,setLanguage,get language(){return language}};
})();
