function tr(ja,en){return AssemblyI18n.language==='ja'?ja:en}
function candidatePartition(items,key,observed={}){const groups={},unknown=[];for(const item of items){const value=expectedPhenotypes(item,observed)[key];if(value)(groups[value]??=[]).push(item);else unknown.push(item)}const counts=Object.values(groups).map(a=>a.length);const separated=counts.reduce((sum,n,i)=>sum+n*counts.slice(i+1).reduce((a,b)=>a+b,0),0);return {groups,unknown,separated}}
function renderNextObservations(ranked){
 const host=$('#nextObservations');if(!ranked){host.innerHTML=`<p>${tr('まず観察済みの表現型を選択してください。','Select an observed phenotype first.')}</p>`;return}
 const compatible=ranked.filter(r=>r.conflict.length===0),items=compatible.map(r=>r.item);
 if(!items.length){host.innerHTML=`<p>${tr('矛盾のない候補がありません。入力と未収載の原因を再検討してください。','No candidate is consistent with all observations. Reconsider inputs and causes outside this catalog.')}</p>`;return}
 const observed=Object.fromEntries(phenotypeFields.map(([key])=>[key,$('#phenotype-'+key).value]));
 const proposals=phenotypeFields.filter(([key])=>!observed[key]).map(([key,label,options])=>({key,label,options,...candidatePartition(items,key,observed)})).filter(p=>p.separated>0).sort((a,b)=>b.separated-a.separated);
 host.innerHTML=`<p>${tr('矛盾のない候補','Candidates without conflicts')}: ${items.length}. ${tr('既知の予測値が異なる候補ペアを多く分ける項目から表示。未判定の候補は、どの結果でも残ります。確率や診断精度ではありません。','Ranked by the number of candidate pairs with different known predictions. Unknown candidates remain possible for every outcome. This is not probability or diagnostic accuracy.')}</p>`+(proposals.length?proposals.map(p=>`<article class="next-card"><h3>${p.label}</h3><p>${tr('区別できる候補ペア','Distinguishable candidate pairs')}: ${p.separated} · ${tr('未判定','Unknown')}: ${p.unknown.length}</p>${Object.entries(p.options).map(([value,label])=>`<button type="button" data-observe="${p.key}" data-value="${value}">${label} · ${tr('残る候補','Remaining')}: ${(p.groups[value]?.length||0)+p.unknown.length}</button>`).join('')}<details><summary>${tr('結果ごとの候補を確認','Inspect candidates by outcome')}</summary>${Object.entries(p.options).map(([value,label])=>`<p>${label}: ${(p.groups[value]||[]).map(x=>'Δ'+x.gene).join(', ')||'—'}</p>`).join('')}<p>${tr('未判定（除外しない）','Unknown (not excluded)')}: ${p.unknown.map(x=>'Δ'+x.gene).join(', ')||'—'}</p></details></article>`).join(''):`<p>${tr('現在の収載項目では、これ以上候補を区別できません。遺伝子群内の識別や未収載の表現型には追加資料が必要です。','The remaining candidates cannot be separated using the available observations. Distinguishing genes within grouped entries or unlisted phenotypes requires additional evidence.')}</p>`);
 host.querySelectorAll('[data-observe]').forEach(b=>b.onclick=()=>{$('#phenotype-'+b.dataset.observe).value=b.dataset.value;renderPredictions()});
}
function renderWildtypeComparison(item){
 const wt={key:'wildtype',mode:'wildtype',stage:9,impact:-1};
 renderDiagram(wt,'#wildtypeDiagram','#wildtypeRail');renderDiagram(item,'#mutantDiagram','#mutantRail');
 $('#mutantHeading').textContent='Δ'+item.gene;$('#comparisonSpecies').textContent=species[state.species].name;
 const labels={built:tr('構築モデル','Modeled as built'),affected:tr('影響点','Affected'),absent:tr('未形成モデル','Modeled as absent'),warn:tr('異常・条件依存・未判定','Altered / conditional / unknown')};
 const stages=stageNames.map((name,i)=>({name,i,status:stateFor(i,item)})).filter(x=>!(state.species==='bacillus'&&x.i===4));
 $('#wildtypeDifferences').innerHTML=`<table><thead><tr><th>${tr('段階','Stage')}</th><th>WT</th><th>Δ${item.gene}</th></tr></thead><tbody>${stages.map(s=>`<tr class="${s.status!=='built'?'difference':''}"><td>${s.name}</td><td>${labels.built}</td><td>${labels[s.status]}</td></tr>`).join('')}</tbody></table><p>${tr('野生型は形成・回転が可能な基準モデルです。実測対照ではありません。配置・本数や不安定性は模式図だけでは十分に表現できません。','WT is a reference model capable of assembly and rotation, not a measured control. The schematic does not fully represent changes in placement, number or stability.')}</p>`;
}
function renderEvidence(item){
 const observed=Object.fromEntries(phenotypeFields.map(([key])=>[key,$('#phenotype-'+key)?.value||'']));
 const f=expectedPhenotypes(item,observed),grouped=geneNames(item).length>1;
 return `<section class="evidence-audit"><h3>${tr('表現型ごとの根拠','Evidence by phenotype')}</h3><p>${tr('表は照合ルールのモデル推定です。原著の観察記録そのものではありません。欠損条件・株・培地・温度との対応は一部確認にとどまります。','This table contains model rules, not experimental observation records. Deletion conditions, strain, medium and temperature are only partially reviewed.')}</p>${item.rotationConditional?`<p>${tr('FliH/I/J群：ロッド形成が観察された場合のみ、回転可能と照合します。未観察なら回転は未判定です。','FliH/I/J group: rotation is matched as possible only when an assembled rod is observed. Without that observation, rotation remains unknown.')}</p>`:''}<div class="evidence-scroll"><table><thead><tr><th>${tr('観察項目','Observation')}</th><th>${tr('予測','Prediction')}</th><th>${tr('根拠区分','Evidence class')}</th></tr></thead><tbody>${phenotypeFields.map(([key,label,options])=>`<tr><td>${label}</td><td>${f[key]?options[f[key]]:tr('未判定','Unknown')}</td><td>${f[key]?tr('モデル推定','Model inference'):tr('未収載','Not curated')}</td></tr>`).join('')}</tbody></table></div><p>${tr('対象範囲','Catalog scope')}: ${species[state.species].strain}</p>${grouped?`<p class="caution">${tr('複数遺伝子をまとめたカードです。各遺伝子の単独欠損や、全遺伝子の同時欠損が同じ表現型になることを保証しません。','This entry groups multiple genes. Identical phenotypes are not established for each single deletion or their combined deletion.')}</p>`:''}${item.auditNote?`<h3>${tr('確認した文献の記載','Reviewed source detail')}</h3><p>${tr(item.auditNote.ja,item.auditNote.en)}</p>`:''}<h3>${tr('背景・関連原著','Background / related primary papers')}</h3><p>${tr('リンク先の菌種と変異を確認してください。関連する構造・役割の論文を、全欠損表現型の直接証拠とはみなしません。','Check the organism and mutation in each source. A paper on a related structure or function is not direct evidence for every deletion phenotype.')}</p>${item.refs.length?item.refs.map(r=>`<a class="detail-source" href="${r.url}" target="_blank" rel="noopener noreferrer">${r.label} ↗</a>`).join(''):`<p>${tr('適用できる原著の対応付けは未完了です。','Applicable primary-source mapping is not yet available.')}</p>`}</section>`;
}
function renderReviewNotice(){
 $('#uncertainLegend').textContent=tr('異常・条件依存・未判定','Altered / conditional / unknown');
 $('#auditNotice').innerHTML=`<strong>${tr('研究・教育用の探索モデル · 内容点検 2026-09-23','Exploratory research / teaching model · reviewed 2026-09-23')}</strong><p>${tr('全べん毛遺伝子を網羅したデータベースではありません。図は非定量の構築モデルで、候補順位は確率ではありません。Vibrioは極べん毛のみを対象とします。','This is not an exhaustive database of flagellar genes. Diagrams are qualitative assembly models and candidate rankings are not probabilities. Only the polar flagellum is modeled for Vibrio.')}</p><details><summary>${tr('図・回転・候補の読み方','Interpreting diagrams, rotation and candidates')}</summary><p>${tr('淡色の構造は未形成を表す輪郭です。赤は影響点で、構造の存在を保証しません。黄は異常・条件依存・未判定を含みます。回転判定が不明な場合も動画を止めるため、静止表示は回転停止の証拠ではありません。WTの反時計回りは細胞外側から見た説明用の表示で、速度・方向切替・サブユニット数を再現していません。膜は簡略化した二重層で、外膜のLPS非対称性は省略しています。','Faint structures are outlines of modeled absent components. Red marks an affected site, not guaranteed structural presence. Yellow includes altered, conditional and unknown states. Animation also pauses when rotation is unknown; a static image is not evidence of motor arrest. WT rotates counterclockwise as viewed from outside the cell for illustration only; speed, switching and subunit stoichiometry are not simulated. Bilayers are simplified; outer-membrane LPS asymmetry is omitted.')}</p><p>${tr('群カードは各単独欠損の等価性を保証しません。比較欄の空欄は未収載で、遺伝子が存在しないという意味ではありません。追加観察では実際に得た結果だけを入力してください。菌種を変更すると観察入力はリセットされます。','Grouped entries do not establish equivalence of individual deletions. Missing comparison entries mean not cataloged, not gene absence. Enter only measured outcomes in the observation suggestions. Changing species resets observations.')}</p></details>`;
}
